---
title: "Qui sont les participants de la l'atelier R ?"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---


```{r acquire_data}
if (!require("pacman")) install.packages("pacman")
pacman::p_load("googlesheets4",
               "dplyr",
               "flexdashboard",
               "ggplot2",
               "ggmap",
               "sp")

# lecture des réponses

answers <- read_sheet("https://docs.google.com/spreadsheets/d/1c3KLpUF0qQTFhZVlxK13DwKTG5y0fr2Wat4RbqjUIYE/edit#gid=408559949")

df <- answers 
```



Column
-----------------------------------------------------------------------

### Nombre de répondants {.value-box}

```{r}
valueBox(nrow(df), icon = "ion-person-stalker")

```


### Sexe

```{r}

taux <- sum(df$`Vous êtes` == "Une femme", na.rm = TRUE) / nrow(df) * 100
gauge(round(taux), 0, 100, symbol = "%", sectors = gaugeSectors(success = c(50,100), warning = c(0, 49)))

```

### Âge

```{r}
ggplot(df, aes(x = `Vous avez`)) +
  geom_bar(fill = "#a65455") +
  ylab("") +
  theme_bw() +
  theme(text = element_text(size=20),
        axis.text.x = element_text(angle=45, hjust=1))  

```

Column
-----------------------------------------------------------

### Niveau en programmation R

```{r}
ggplot(df, aes(x = `Votre niveau en programmation R`)) +
  geom_bar(fill = "steelblue") +
  ylab("") +
  theme(text = element_text(size=20))  

```


### RMarkdown 

```{r}

taux <- sum(df$`Avez-vous déjà utilisé RMarkdown ?` == "Oui", na.rm = TRUE) / nrow(df) * 100
gauge(round(taux), 0, 100, symbol = "%", sectors = gaugeSectors(success = c(50,100), warning = c(0, 49)))

```




